sudo: required

language: python

python:
  - "2.7"

node_js:
  - "node"
  - "7"
  - "6"
  - "5"
  - "4"

cache:
  directories:
    - $HOME/.cache/pip

  before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install:
  - pip install -r requirements/dev.txt

script:
  - flake8 ./
  - npm run ci
