dist: trusty
sudo: required

language: python

python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip
    # - $HOME/caffe

  before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements/dev.txt
  - . $HOME/.nvm/nvm.sh
  - sh requirements/caffe_tensorflow_keras_install.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_script:
  - export PYTHONPATH=$PYTHONPATH:$HOME/caffe/caffe/python
script:
  - flake8 ./
  - npm run ci
  - KERAS_BACKEND=theano coverage run --source=caffe_app,keras_app,ide/utils manage.py test

after_success:
  - coveralls
